steps:
  - name: test
    image: node:15.4.0-alpine
    commands:
      - npm test

  - name: check workspace
    image: ubuntu
    commands:
      - cat testfile | grep "straight up chillen"

  - name: a new step
    image: ubuntu
    commands:
      - echo "workspace is shared between steps"
      - ls
      - echo "this will be triggered via webhooks"
